export const SET_USERNAME_AND_ID = "SET_USERNAME_AND_ID";
export const REMOVE_CONNECTED_USER = "REMOVE_CONNECTED_USER";
export const ADD_CONNECTED_USER = "ADD_CONNECTED_USER";
export const ADD_TO_MESSAGES = "ADD_TO_MESSAGES";
export const SET_CONNECTED_USERS = "SET_CONNECTED_USERS";
export const SET_MESSAGE_TO_SOCKET_ID = "SET_MESSAGE_TO_SOCKET_ID";
export const ADD_TO_PERSONAL_MESSAGES = "ADD_TO_PERSONAL_MESSAGES";
export const SET_CHAT_STATE = "SET_CHAT_STATE";
