export const SET_USERNAME_AND_ID = "SET_USERNAME_AND_ID";
export const REMOVE_CONNECTED_USER = "REMOVE_CONNECTED_USER";
export const ADD_CONNECTED_USER = "ADD_CONNECTED_USER";
export const ADD_TO_MESSAGES = "ADD_TO_MESSAGES";
